---
# tasks file for eksctl | Debian/Ubuntu Family

- name: Debian/Ubuntu Family | Downloading and extracting {{ eksctl_app }} {{ eksctl_version }}
  unarchive:
    src: "{{ eksctl_dl_url }}"
    dest: "{{ eksctl_bin_path }}"
    extra_opts:
      - eksctl
    remote_src: yes
    owner: "{{ eksctl_file_owner }}"
    group: "{{ eksctl_file_group }}"
